# Generated by Django 2.2.6 on 2021-01-25 11:08

from django.db import migrations, models
import django.db.models.deletion
import sbs.models.EnumFields


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gkira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('sahibi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Taşınmazın Sahibi')),
                ('onayTarihi', models.DateTimeField(blank=True, null=True)),
                ('sozlesmeTarihi', models.DateTimeField(blank=True, null=True)),
                ('sozlesmeSonTarihi', models.DateTimeField(blank=True, null=True)),
                ('kiralamaSuresi', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sözlemşme Bitis Tarihi')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Tasınmazin Kira Adresi')),
                ('kapalialan', models.IntegerField(blank=True, null=True)),
                ('tahsis_amaci', models.CharField(choices=sbs.models.EnumFields.EnumFields((('Ceza İnfaz Kurumu', 'Ceza İnfaz Kurumu'), ('Adalet Binası', 'Adalet Binası'), ('Adli Tıp', 'Adli Tıp'), ('Bölge Adliye Mahkemesi', 'Bölge Adliye Mahkemesi'), ('Bölge İdare Mahkemesi', 'Bölge İdare Mahkemesi'), ('Denetimli Serbestlik', 'Denetimli Serbestlik'), ('Bakanlık Binası', 'Bakanlık Bİnası'), ('Personel Eğitim Merkezi', 'Personel Eğitim Merkezi'), ('Lojman', 'Lojman'), ('SOSYAL TESİS ', 'Sosyal Tesis'), ('HAKİM EVİ', 'Hakim Evi'), ('Diğer', 'Diğer'))), max_length=128, verbose_name='Kullanim Amaci')),
                ('block', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('UsageArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GkiraBedeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('kiraTarihi', models.DateTimeField()),
                ('kiraBedeli', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gkurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gtahsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('tahsisTarihi', models.DateTimeField(blank=True, null=True)),
                ('tahsisSuresi', models.CharField(max_length=128, verbose_name='Tahsis Süresi')),
                ('tahsis_amaci', models.CharField(choices=sbs.models.EnumFields.EnumFields((('Ceza İnfaz Kurumu', 'Ceza İnfaz Kurumu'), ('Adalet Binası', 'Adalet Binası'), ('Adli Tıp', 'Adli Tıp'), ('Bölge Adliye Mahkemesi', 'Bölge Adliye Mahkemesi'), ('Bölge İdare Mahkemesi', 'Bölge İdare Mahkemesi'), ('Denetimli Serbestlik', 'Denetimli Serbestlik'), ('Bakanlık Binası', 'Bakanlık Bİnası'), ('Personel Eğitim Merkezi', 'Personel Eğitim Merkezi'), ('Lojman', 'Lojman'), ('SOSYAL TESİS ', 'Sosyal Tesis'), ('HAKİM EVİ', 'Hakim Evi'), ('Diğer', 'Diğer'))), max_length=128, verbose_name='Proje Cinsi')),
                ('emsal', models.CharField(max_length=128, verbose_name='Tahsis Süresi')),
                ('tahsis_kurum', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='sbs.Gkurum', verbose_name='Tahsis Eden Kurum')),
            ],
        ),
        migrations.CreateModel(
            name='GTapu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=120, null=True)),
                ('parcel', models.CharField(max_length=120, null=True)),
                ('island', models.CharField(max_length=120, null=True)),
                ('neighborhood', models.TextField(blank=True, null=True, verbose_name='Mahallle')),
                ('location', models.TextField(blank=True, null=True, verbose_name='konum')),
            ],
        ),
        migrations.CreateModel(
            name='Gteskilat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('depremderecesi', models.CharField(choices=sbs.models.EnumFields.EnumFields((('1.DERECE', '1.DERECE'), ('2.DERECE', '2.DERECE'), ('3.DERECE', '3.DERECE'), ('4.DERECE', '4.DERECE'), ('5.DERECE', '5.DERECE'))), max_length=128, verbose_name='deprem derecesi')),
                ('yargiBolgesi', models.CharField(choices=sbs.models.EnumFields.EnumFields((('1.BÖLGE', '1.BÖLGE'), ('2.BÖLGE', '2.BÖLGE'), ('3.BÖLGE', '3.BÖLGE'), ('4.BÖLGE', '4.BÖLGE'), ('5.BÖLGE', '5.BÖLGE'))), max_length=128, verbose_name='Yargi Bölgesi')),
                ('merkeznufus', models.IntegerField(blank=True, null=True)),
                ('yargiAlaniNufus', models.IntegerField(blank=True, null=True)),
                ('agırCezaMerkezi', models.CharField(blank=True, max_length=128, null=True)),
                ('asliyeCezaMerkezi', models.CharField(blank=True, max_length=128, null=True)),
                ('hakim_sayisi', models.CharField(blank=True, max_length=128, null=True)),
                ('savci_sayisi', models.IntegerField(blank=True, null=True)),
                ('personel_sayisi', models.IntegerField(blank=True, null=True)),
                ('UsageArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': ()},
        ),
        migrations.CreateModel(
            name='Gtasinmaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('sirano', models.IntegerField(blank=True, null=True)),
                ('tkgmno', models.IntegerField(blank=True, null=True)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('UsageArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('mulkiyet', models.CharField(choices=[('HAZİNE', 'HAZİNE'), ('HÜKÜMET KONAGI İÇERİSİNDE', 'HÜKÜMET KONAĞI İÇİNDE'), ('HÜKÜMET KONAGI AYRİ BLOK', 'HÜKÜMET KONAĞINDA AYRI BLOK'), ('İŞ YURTLARI', 'İŞ YURTLARI'), ('DİĞER KAMU KURUM KURULUŞLARINA AİT YAPILAR', 'DİĞER KAMU KURUM KURULUŞLARINA AİT YAPILAR')], max_length=128, verbose_name='Mülkiyet ')),
                ('kira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbs.Gkira', verbose_name='Kurum')),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbs.Gkurum', verbose_name='Kurum')),
                ('tahsis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbs.Gtahsis', verbose_name='Kurum')),
                ('tapu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbs.GTapu', verbose_name='Tapu')),
            ],
        ),
        migrations.AddField(
            model_name='gtapu',
            name='city',
            field=models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.SET_NULL, to='sbs.City', verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='gtapu',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.SET_NULL, to='sbs.Country', verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='gtapu',
            name='town',
            field=models.ForeignKey(db_column='town', on_delete=django.db.models.deletion.SET_NULL, to='sbs.Town', verbose_name='İlce'),
        ),
        migrations.AddField(
            model_name='gtahsis',
            name='tapu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='sbs.GTapu', verbose_name='Tahsisli Arsa Tapu'),
        ),
        migrations.AddField(
            model_name='gkira',
            name='kirabedeli',
            field=models.ManyToManyField(to='sbs.GkiraBedeli'),
        ),
    ]
