# Generated by Django 2.2.6 on 2021-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0002_auto_20210125_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtasinmaz',
            name='tahsis_durumu',
            field=models.CharField(choices=[('Tahsisli Arsa', 'Tahsisli Arsa '), ('Kiralık', 'Kiralık')], default=1, max_length=128, verbose_name='Tahsis durumu '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtasinmaz',
            name='tasinmazinTuru',
            field=models.CharField(choices=[('Ceza İnfaz Kurumu', 'Ceza İnfaz Kurumu'), ('Adalet Binası', 'Adalet Binası'), ('Adli Tıp', 'Adli Tıp'), ('Bölge Adliye Mahkemesi', 'Bölge Adliye Mahkemesi'), ('Bölge İdare Mahkemesi', 'Bölge İdare Mahkemesi'), ('Denetimli Serbestlik', 'Denetimli Serbestlik'), ('Bakanlık Binası', 'Bakanlık Bİnası'), ('Personel Eğitim Merkezi', 'Personel Eğitim Merkezi'), ('Lojman', 'Lojman'), ('SOSYAL TESİS ', 'Sosyal Tesis'), ('HAKİM EVİ', 'Hakim Evi'), ('Diğer', 'Diğer')], default=1, max_length=128, verbose_name='Tasinmazin Türü '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gtasinmaz',
            name='UsageArea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gtasinmaz',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
