# Generated by Django 2.2.6 on 2021-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0003_auto_20210125_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtasinmaz',
            name='mulkiyet',
            field=models.CharField(choices=[('HAZİNE', 'HAZİNE'), ('HÜKÜMET KONAGI İÇERİSİNDE', 'HÜKÜMET KONAĞI İÇİNDE'), ('HÜKÜMET KONAGI AYRİ BLOK', 'HÜKÜMET KONAĞINDA AYRI BLOK'), ('İŞ YURTLARI', 'İŞ YURTLARI'), ('DİĞER KAMU KURUM KURULUŞLARINA AİT YAPILAR', 'DİĞER KAMU KURUM KURULUŞLARINA AİT YAPILAR')], default='HAZİNE', max_length=128, verbose_name='Mülkiyet '),
        ),
        migrations.AlterField(
            model_name='gtasinmaz',
            name='tahsis_durumu',
            field=models.CharField(choices=[('Tahsisli Arsa', 'Tahsisli Arsa '), ('Kiralık', 'Kiralık')], default='Tahsisli Arsa', max_length=128, verbose_name='Tahsis durumu '),
        ),
        migrations.AlterField(
            model_name='gtasinmaz',
            name='tasinmazinTuru',
            field=models.CharField(choices=[('Ceza İnfaz Kurumu', 'Ceza İnfaz Kurumu'), ('Adalet Binası', 'Adalet Binası'), ('Adli Tıp', 'Adli Tıp'), ('Bölge Adliye Mahkemesi', 'Bölge Adliye Mahkemesi'), ('Bölge İdare Mahkemesi', 'Bölge İdare Mahkemesi'), ('Denetimli Serbestlik', 'Denetimli Serbestlik'), ('Bakanlık Binası', 'Bakanlık Bİnası'), ('Personel Eğitim Merkezi', 'Personel Eğitim Merkezi'), ('Lojman', 'Lojman'), ('SOSYAL TESİS ', 'Sosyal Tesis'), ('HAKİM EVİ', 'Hakim Evi'), ('Diğer', 'Diğer')], default='Adalet Binası', max_length=128, verbose_name='Tasinmazin Türü '),
        ),
    ]
