# Generated by Django 2.2.6 on 2021-01-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0004_auto_20210125_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtasinmaz',
            name='definition',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tasınmaz Açıklama '),
        ),
    ]
