# Generated by Django 2.2.6 on 2021-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0005_gtasinmaz_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtasinmaz',
            name='arsaDegeri',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gtasinmaz',
            name='yapiMalitet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gtasinmaz',
            name='yapiRaic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
