# Generated by Django 2.2.6 on 2021-02-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0006_auto_20210125_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gkira',
            name='kirabedeli',
        ),
        migrations.RemoveField(
            model_name='gtahsis',
            name='tahsis_kurum',
        ),
        migrations.RemoveField(
            model_name='gtahsis',
            name='tapu',
        ),
        migrations.RemoveField(
            model_name='gtapu',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gtapu',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gtapu',
            name='town',
        ),
        migrations.RemoveField(
            model_name='gtasinmaz',
            name='kira',
        ),
        migrations.RemoveField(
            model_name='gtasinmaz',
            name='kurum',
        ),
        migrations.RemoveField(
            model_name='gtasinmaz',
            name='tahsis',
        ),
        migrations.RemoveField(
            model_name='gtasinmaz',
            name='tapu',
        ),
        migrations.DeleteModel(
            name='Gteskilat',
        ),
        migrations.AddField(
            model_name='company',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='directorymemberrole',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epdocument',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epemployee',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epneeddocument',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epoffer',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epphase',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epproject',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='eprequirements',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='epvest',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='grupforreport',
            name='kobilid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Gkira',
        ),
        migrations.DeleteModel(
            name='GkiraBedeli',
        ),
        migrations.DeleteModel(
            name='Gkurum',
        ),
        migrations.DeleteModel(
            name='Gtahsis',
        ),
        migrations.DeleteModel(
            name='GTapu',
        ),
        migrations.DeleteModel(
            name='Gtasinmaz',
        ),
    ]
